spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 600000
      leak-detection-threshold: 15000
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT}

logging:
  level:
    org.hibernate.SQL: debug  # Hibernate SQL 로그만 켬
    org.hibernate.orm.jdbc.bind: trace  # 파라미터 로그 유지